// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEwnKsFpthlaFhQY3Bz5BKVcpMFT9mSw8',
    appId: '1:321739233292:web:3fe6df45464b9ab5c2b629',
    messagingSenderId: '321739233292',
    projectId: 'unsplah-api-project',
    authDomain: 'unsplah-api-project.firebaseapp.com',
    storageBucket: 'unsplah-api-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNBDzIlRFKjiu6h7F3Y1Jd7KOzrT_9Yq4',
    appId: '1:321739233292:android:ca59512a8fc01d88c2b629',
    messagingSenderId: '321739233292',
    projectId: 'unsplah-api-project',
    storageBucket: 'unsplah-api-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe5_u8Z3CJqhkB3CCnlvqS13X3HVPUDUM',
    appId: '1:321739233292:ios:b6ba89f80ba8cf6cc2b629',
    messagingSenderId: '321739233292',
    projectId: 'unsplah-api-project',
    storageBucket: 'unsplah-api-project.appspot.com',
    iosClientId: '321739233292-a6s5shgsjc7o1mbdg5as0l6rk3748goq.apps.googleusercontent.com',
    iosBundleId: 'com.example.unsplasnapi',
  );
}
